version: '3.9'

services:
  app:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8001"
    restart: always
    ports: 
      - 8001:8001
    volumes:
      - app_data:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

volumes:
  app_data: